on:
  workflow_call:
jobs:
  pre-commit:
    uses: ./.github/workflows/tox-pre-commit.yml
    with:
      py-version: "3.9"
  build:
    uses: ./.github/workflows/tox-build.yml
    with:
      py-version: "3.9"
  tests:
    strategy:
      matrix:
        py-version: [ "3.9" ]
    uses: ./.github/workflows/package-tox-tests.yml
    with:
      py-version: ${{ matrix.py-version }}
