on:
  workflow_call:
    inputs:
      py-version:
        required: true
        type: string
jobs:
  download-windows-dependencies:
    runs-on: windows-2019
    name: windows dependencies py ${{ inputs.py-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.py-version }}
          architecture: "x86"
      - name: Download dependencies
        run: pip download -r src/requirements.txt -d dependencies
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-dependencies
          path: dependencies
