name: check version
on:
  workflow_call:
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get current version
        id: currentVersion
        uses: mikefarah/yq@v4
        with:
          cmd: yq e ".metadata.template_version" shell-definition.yaml
      - name: Save shell-definition.yaml from master
        run: |
          git clone https://github.com/${{ github.repository }}.git ${{ github.repository }}
          BASE_DIR=`pwd`
          cd ${{ github.repository }}
          git checkout -qf ${{ github.head_ref }}
          git show master:shell-definition.yaml > $BASE_DIR/tmp.yaml
      - name: Get master version
        id: masterVersion
        uses: mikefarah/yq@v4
        with:
          cmd: yq e ".metadata.template_version" tmp.yaml
      - name: Check version
        run: |
          ! diff <(echo "${{ steps.currentVersion.outputs.result }}") <(echo "${{ steps.masterVersion.outputs.result }}")
