on: workflow_call
jobs:
  download-centos-dependencies-py39:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
    container: centos:7
    name: centos dependencies py 39
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 39
        run: |
          sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/CentOS-*.repo
          sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/CentOS-*.repo
          sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/CentOS-*.repo
          yum -y install wget make gcc openssl-devel bzip2-devel libffi-devel
          wget https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz
          tar xzf Python-3.9.9.tgz
          cd Python-3.9.9
          ./configure --enable-optimizations
          make altinstall
          cd ..
      - name: Update setuptools and pip
        run: /usr/local/bin/pip3.9 install -U setuptools pip
      - name: Download dependencies
        run: /usr/local/bin/pip3.9 download -r src/requirements.txt -d dependencies
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-dependencies
          path: dependencies
