on:
  workflow_call:
jobs:
  pre-commit:
    uses: ./.github/workflows/tox-pre-commit.yml
  pack:
    uses: ./.github/workflows/shell-tox-pack.yml
  download-linux-dep:
    uses: ./.github/workflows/shell-download-linux-dep.yml
    strategy:
      matrix:
        py-version: [ "3.7", "3.9" ]
    with:
      py-version: ${{ matrix.py-version }}
  download-centos-py37-dep:
    uses: ./.github/workflows/shell-download-centos7-py37-dep.yml
  download-centos-py39-dep:
    uses: ./.github/workflows/shell-download-centos7-py39-dep.yml
  download-win-dep:
    uses: ./.github/workflows/shell-download-win-dep.yml
    strategy:
      matrix:
        py-version: [ "3.7", "3.9" ]
    with:
      py-version: ${{ matrix.py-version }}
  validate-shell-name:
    uses: ./.github/workflows/shell-validate-name.yml
