on:
  workflow_call:
    inputs:
      run-pre-commit:
        required: false
        type: boolean
        default: true
jobs:
  pre-commit:
    if: ${{ inputs.run-pre-commit == true }}
    uses: ./.github/workflows/tox-pre-commit.yml
    with:
      py-version: "3.9"
  pack:
    uses: ./.github/workflows/shell-tox-pack.yml
  download-centos-py39-dep:
    uses: ./.github/workflows/shell-download-centos7-py39-dep.yml
  download-linux-dep:
    uses: ./.github/workflows/shell-download-linux-dep.yml
    strategy:
      matrix:
        py-version: [ "3.9" ]
    with:
      py-version: ${{ matrix.py-version }}
  download-win-dep:
    uses: ./.github/workflows/shell-download-win-dep.yml
    strategy:
      matrix:
        py-version: [ "3.9" ]
    with:
      py-version: ${{ matrix.py-version }}
  validate-shell-name:
    uses: ./.github/workflows/shell-validate-name.yml
