on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ${{ github.ref }}
jobs:
  pack:
    name: Pack the Shell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install tox
      - name: Build
        env:
          TOXENV: pack
        run: tox
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: shell
          path: dist/*
