on:
  workflow_call:
    inputs:
      py-version:
        required: true
        type: string
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.py-version }}
      - name: Install dependencies
        run: pip install tox
      - name: Run pre-commit
        env:
          TOXENV: pre-commit
        run: tox
