on:
  workflow_call:
    inputs:
      py-version:
        required: true
        type: string
jobs:
  check-mypy-present:
    name: check mypy present
    runs-on: ubuntu-latest
    outputs:
      mypy-present: ${{ steps.check-mypy.outputs.mypy-present }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check mypy is present in tox
        id: check-mypy
        run: |
          if grep -q "^\[testenv:mypy\]" tox.ini; then
            echo "mypy environment found in tox.ini"
            echo "mypy-present=true" >> "$GITHUB_OUTPUT"
          else
            echo "mypy environment not found in tox.ini"
            echo "mypy-present=false" >> "$GITHUB_OUTPUT"
          fi
  mypy:
    name: check mypy ${{ inputs.py-version }}
    runs-on: ubuntu-latest
    needs: check-mypy-present
    if: needs.check-mypy-present.outputs.mypy-present == 'true'
    steps:
      - name: Set up Python ${{ inputs.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.py-version }}
      - name: Install dependencies
        run: pip install tox
      - name: mypy
        env:
          TOXENV: mypy
        run: tox
