on:
  workflow_call:
    inputs:
      py-version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.py-version }}
      - name: Install dependencies
        run: pip install tox
      - name: Build
        env:
          TOXENV: build
        run: tox
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package files
          path: dist/*
